// 12-season color analysis data — single source of truth.
// Mirrors the JS object in /public/index.html for server-side rendering.

export const SEASONS = {
  "Bright Spring": {
    coords: { warmth: 0.5, value: 0.4, chroma: 0.9 },
    tagline: "Vivid, clear, and quietly electric.",
    palette: [["Lemon Zest","#F5E04A"],["Tangerine","#F08A45"],["Coral Pop","#F0625A"],["Watermelon","#E14A6B"],["Hot Magenta","#C73883"],["Periwinkle","#7F89D8"],["Bright Aqua","#3FBFC2"],["Spring Leaf","#4ABE5A"],["Apple Green","#9FCC3A"],["Buttercup","#FFC83B"],["Coral Crush","#FF8474"],["Pure White","#FAFAFA"],["Bright Navy","#1E3A8A"],["Sky Blue","#5BC2E7"],["Hot Pink","#E84B8B"],["Acid Yellow","#E5DC2E"],["Clear Red","#E63946"],["Iris","#6A5ACD"]],
    neutrals: [["Stone","#D6CFC4"],["Camel","#C19A6B"],["Bright Navy","#1E3A8A"],["Warm Ivory","#F5EFE3"],["Cocoa","#6B4F3B"]],
    avoid: [["Dusty Mauve","#A38A8A","Mutes your clarity"],["Olive Drab","#6E6B3E","Drains warmth"],["Burgundy","#6B1F2F","Too heavy"],["Charcoal","#2A2A2A","Overpowers"],["Beige","#C9B59A","Reads dull"]],
    metals: { title: "Gold and yellow gold", text: "Bright, polished yellow gold lights you up. Skip antiqued or matte finishes — keep metals shiny and clear.", swatches: ["#E8C547","#F2D680","#C9A36B"] },
    prints: { title: "Bold, graphic, clear-colored", text: "Bold, graphic prints in clear colors. High contrast geometrics, crisp florals — avoid washed, watercolor prints." },
    makeup: { title: "Coral, peach, bronze", text: "Coral and warm pink lips, peach blush, bronze and warm taupe eyes. Stay clear and pigmented — nothing dusty.", swatches: ["#FF8474","#E84B8B","#C9A36B"] },
    clothing: { title: "Crisp, saturated, clean-lined", text: "Clean tailoring in saturated brights — a clear coral blazer, true-navy trousers, crisp white shirting. Smooth, fresh fabrics (poplin, gabardine, structured knits) hold your clarity; keep silhouettes sharp rather than draped." },
    jewelry: { title: "Polished gold, clear stones", text: "Bright yellow gold set with vivid, transparent stones — turquoise, clear topaz, coral, peridot. Choose glossy finishes and defined shapes; skip anything oxidized, matte, or muddy." },
    meaning: "You are spring's bright morning — features that look hand-painted in clear pigment. Your job is to never mute yourself."
  },
  "True Spring": {
    coords: { warmth: 0.9, value: 0.4, chroma: 0.6 },
    tagline: "Sunlit, golden, and warmly alive.",
    palette: [["Daffodil","#F5C84C"],["Marigold","#E89B3C"],["Salmon","#F5876E"],["Warm Coral","#E66A4C"],["Apricot","#F5A572"],["Camel","#C19A6B"],["Warm Turquoise","#3FB5A8"],["Grass Green","#62A744"],["Golden Olive","#A89B3F"],["Honey","#D8A856"],["Tomato Red","#E04A3C"],["Cream","#F5EFE0"],["Warm Beige","#D6B894"],["Peach","#F5C2A0"],["Sage","#9BB57E"],["Caramel","#B07A4F"],["Buttercream","#F0E2BC"],["Terracotta","#C66A4F"]],
    neutrals: [["Cream","#F5EFE0"],["Camel","#C19A6B"],["Warm Brown","#7A5236"],["Navy with warmth","#324A6B"],["Stone","#D6CFC4"]],
    avoid: [["Pure Black","#0A0A0A","Too harsh"],["Cool Pink","#E89BC4","Cools you down"],["Icy Blue","#BDD9E8","Drains warmth"],["Burgundy","#6B1F2F","Heavy and cool"],["Pure White","#FFFFFF","Off — choose cream"]],
    metals: { title: "Yellow gold and brass", text: "Warm yellow gold, polished brass, and antique gold are your signature. Silver looks chilly against your skin.", swatches: ["#D4AF37","#C9A36B","#A87932"] },
    prints: { title: "Painterly florals, paisleys", text: "Painterly florals, paisleys, and earthy ditsy prints. Medium scale, organic shapes — bring on the warmth." },
    makeup: { title: "Coral, peach, warm nude", text: "Coral, peach, and warm nude lips. Peachy blush, bronze and warm green eyes. Foundation must be warm-yellow undertone.", swatches: ["#F5876E","#E89B3C","#9BB57E"] },
    clothing: { title: "Warm, fresh, lit from within", text: "Golden warmth in fluid-but-crisp pieces — a camel trench, warm coral knit, grass-green shirtdress. Lightweight wool, fine cotton, and light-catching silk suit you; lean warm in every neutral (cream over white, warm navy over black)." },
    jewelry: { title: "Yellow gold, warm stones", text: "Glowing yellow gold and brass with warm stones — citrine, amber, coral, golden pearl. Pieces with a hand-made, sunlit quality flatter you; avoid cool silver and icy white-set diamonds." },
    meaning: "You are golden hour incarnate — wheat fields and citrus groves. Lean into warmth and you become unmistakable."
  },
  "Light Spring": {
    coords: { warmth: 0.4, value: 0.9, chroma: 0.5 },
    tagline: "Airy, gilded, and gently luminous.",
    palette: [["Buttercream","#F5E8B8"],["Soft Peach","#F5C9A8"],["Petal Pink","#F5BFB8"],["Mint","#B8E8C2"],["Sky","#9BC9E0"],["Aqua","#7FCCC0"],["Pastel Yellow","#F5E07A"],["Coral Sand","#F0A28A"],["Light Camel","#D6BC8F"],["Periwinkle","#A8B5E0"],["Cream","#F5EFE0"],["Light Teal","#7FAEAE"],["Pistachio","#C2D699"],["Apricot","#F5BC8F"],["Powder Blue","#BFD6E5"],["Champagne","#E8D6B8"],["Salmon","#F0A290"],["Lilac Sand","#D6B8C9"]],
    neutrals: [["Cream","#F5EFE0"],["Light Camel","#D6BC8F"],["Soft Navy","#5A6B85"],["Warm Taupe","#C2B5A0"],["Ivory","#F5EFE3"]],
    avoid: [["Black","#0A0A0A","Erases you"],["Burgundy","#6B1F2F","Far too heavy"],["Deep Olive","#3F3F1A","Drains the light"],["Charcoal","#2A2A2A","Overpowers"],["Cool Berry","#7A2A4F","Wrong temperature"]],
    metals: { title: "Light gold, rose gold", text: "Delicate gold and soft rose gold complement your luminosity. Skip heavy or oxidized metals.", swatches: ["#F2D680","#E8B8A8","#D4AF7F"] },
    prints: { title: "Small-scale, delicate", text: "Small-scale florals, delicate ditsy prints, gentle watercolors. Low to medium contrast, never bold geometrics." },
    makeup: { title: "Peach, soft coral, luminous", text: "Peach and soft coral lips, blushed cheeks in apricot, golden taupe and soft green eyes. Keep it sheer and luminous.", swatches: ["#F0A28A","#F5BC8F","#D4AF7F"] },
    clothing: { title: "Airy, gilded, gently warm", text: "Light, luminous separates — soft peach, buttercream, mint, periwinkle in flowing-but-tidy shapes. Fine knits, silk, and brushed cotton in pale tints; keep contrast low so nothing overwhelms your delicacy." },
    jewelry: { title: "Delicate gold & rose gold", text: "Fine, light gold and soft rose gold — dainty chains and small pieces with pale stones like aquamarine, rose quartz, opal, and champagne pearl. Skip heavy, dark, or oxidized metals." },
    meaning: "You are first light through linen curtains — soft, warm, impossible to imitate. Whisper your colors and you'll be unforgettable."
  },
  "Light Summer": {
    coords: { warmth: -0.4, value: 0.9, chroma: 0.3 },
    tagline: "Watercolor, dawn-cool, and quietly luminous.",
    palette: [["Powder Pink","#F2C9D6"],["Soft Lilac","#C9B8E0"],["Pale Blue","#B8D4E5"],["Mint","#BFE0D2"],["Cool Lemon","#F0E8A8"],["Periwinkle","#A8B8DE"],["Rose Quartz","#E5B5BF"],["Sky","#9FBFD9"],["Soft Aqua","#A8D6D2"],["Cool Coral","#F0A8B0"],["Iced Apricot","#F5C9B8"],["Lavender","#BFA8D6"],["Soft Yellow","#F5E5A8"],["Powder Blue","#C5D8E5"],["Wisteria","#B5A8D6"],["Cool Beige","#D6CFC4"],["Pearl","#EFE8E0"],["Misty Rose","#E8C9CC"]],
    neutrals: [["Soft White","#F5F0EC"],["Cool Beige","#D6CFC4"],["Rose Brown","#A89090"],["Light Gray","#C5C2BF"],["Soft Navy","#4F5F7F"]],
    avoid: [["Pure Black","#0A0A0A","Too severe"],["Orange","#E66A2C","Wrong temperature"],["Burnt Sienna","#8A4F2F","Drains you"],["Mustard","#A89B3F","Sallows the skin"],["Tomato Red","#E04A3C","Too warm and loud"]],
    metals: { title: "Silver, white gold, platinum", text: "Cool, light metals are your signature. Brushed silver is especially flattering — skip yellow gold.", swatches: ["#D6D6D6","#E8E8E8","#C9C9C9"] },
    prints: { title: "Watercolor, blended", text: "Watercolor florals, soft dots, hand-painted abstracts. Low contrast, blended edges — never bold or graphic." },
    makeup: { title: "Rose, soft pink, dove gray", text: "Rose and cool pink lips, soft pink blush, dove gray and soft mauve eyes. Foundation in cool-pink undertone.", swatches: ["#E5B5BF","#F0A8B0","#BFA8D6"] },
    clothing: { title: "Watercolor-cool & soft", text: "Cool pastels in soft, fluid pieces — powder blue, soft lilac, rose quartz in drapey knits, silk, and brushed cotton. Keep contrast gentle with tonal dressing; avoid stark black-and-white pairings." },
    jewelry: { title: "Brushed silver & pale stones", text: "Cool, light metals — brushed silver, white gold, platinum — with soft cool stones: aquamarine, rose quartz, moonstone, grey pearl. Keep pieces light and delicate; skip yellow gold and heavy statement metals." },
    meaning: "You are an English garden after rain — pastel, cool, and rich beyond first glance. Subtlety is your superpower."
  },
  "True Summer": {
    coords: { warmth: -0.9, value: 0.5, chroma: 0.2 },
    tagline: "Misted, dignified, and beautifully cool.",
    palette: [["Rose","#D69BAA"],["Raspberry","#B85A7F"],["Plum","#7F4A6B"],["Blueberry","#5A6FA8"],["Steel Blue","#5F8AAE"],["Slate","#5F7585"],["Cool Pink","#E5A8B8"],["Periwinkle","#8A99CC"],["Wedgewood","#6B85B5"],["Soft Burgundy","#7F3F4F"],["Cool Berry","#A85A85"],["Misty Teal","#5F8585"],["Powder Blue","#B5C9DE"],["Lilac","#A89BC2"],["Spruce","#3F5F5F"],["Watermelon Pink","#D67A99"],["Dusty Lavender","#9B85AE"],["Cool Burgundy","#7A3F52"]],
    neutrals: [["Soft White","#F0EDE8"],["Cool Gray","#A8A8A8"],["Charcoal Blue","#3F4F5F"],["Cocoa Rose","#8A6B6B"],["Slate","#5F7585"]],
    avoid: [["Orange","#E66A2C","Clashes hard"],["Mustard","#C9A23A","Sallows your skin"],["Pure Black","#0A0A0A","Too harsh"],["Tomato Red","#E04A3C","Wrong undertone"],["Camel","#C19A6B","Drains your cool"]],
    metals: { title: "Silver, white gold", text: "Cool silver, brushed white gold, and platinum are your truest match. Yellow gold reads jaundiced.", swatches: ["#C9C9C9","#D6D6D6","#A8A8A8"] },
    prints: { title: "Liberty florals, soft stripes", text: "Florals on a cool ground, soft Liberty prints, gentle stripes. Medium scale, blended — never harsh contrast." },
    makeup: { title: "Cool rose, berry, slate", text: "Cool rose and berry lips, rosy blush, slate and lavender eyes. Pink-cool foundation; never warm.", swatches: ["#B85A7F","#D69BAA","#7F4A6B"] },
    clothing: { title: "Cool, dignified, romantic", text: "Cool, slightly muted shades — rose, raspberry, soft burgundy, slate blue — in graceful, draped pieces. Matte fabrics (fine wool, jersey, washed silk) suit your softness; choose tonal or low-contrast combinations over high-contrast looks." },
    jewelry: { title: "Silver & cool gemstones", text: "Cool silver, white gold, and platinum with cool stones — sapphire, amethyst, rose and grey pearl. Soft, polished-but-not-flashy pieces flatter; warm gold and amber fight your undertone." },
    meaning: "You are sea mist over a stone garden — cool, dignified, romantic. Lean into softness and depth, never brightness."
  },
  "Soft Summer": {
    coords: { warmth: -0.4, value: 0.3, chroma: -0.6 },
    tagline: "Dusty, refined, and full of secret depth.",
    palette: [["Dusty Rose","#C29097"],["Mauve","#9B7F8C"],["Soft Plum","#7A5F75"],["Sage","#8FA59B"],["Slate Blue","#6B85A0"],["Mushroom","#A89B8F"],["Dusty Teal","#5F8085"],["Cool Taupe","#A89F95"],["Smoky Lavender","#9B8FA8"],["Soft Burgundy","#7F4A55"],["Heather","#A8A0B0"],["Cocoa Pink","#B58A8F"],["Sea Glass","#9BB5B0"],["Pewter","#8F8F8A"],["Misty Mauve","#B59FA8"],["Faded Denim","#7F95AE"],["Soft Coral","#C9907F"],["Driftwood","#A89580"]],
    neutrals: [["Mushroom","#A89B8F"],["Cocoa","#8A6F5F"],["Slate","#5F6F7F"],["Soft White","#F0EAE3"],["Greige","#B5AA9F"]],
    avoid: [["Pure White","#FAFAFA","Too stark"],["Pure Black","#0A0A0A","Too severe"],["Hot Pink","#FF1A8A","Far too bright"],["Acid Yellow","#E5DC2E","Drains your skin"],["Orange","#E66A2C","Wrong temperature"]],
    metals: { title: "Brushed silver, matte rose gold", text: "Antiqued silver, pewter, and soft rose gold are your match. Anything bright or polished overpowers your softness.", swatches: ["#B5B0AA","#C9A8A0","#9F9590"] },
    prints: { title: "Watercolor, faded vintage", text: "Watercolor florals, blended abstracts, faded vintage prints. Low contrast and dusty — never sharp." },
    makeup: { title: "Rose, mauve, taupe", text: "Rose and mauve lips, soft pink blush, taupe and dusty plum eyes. Foundation in soft-cool undertone.", swatches: ["#C29097","#9B7F8C","#A89F95"] },
    clothing: { title: "Dusty, layered, understated", text: "Muted, smoky tones — dusty rose, mauve, sage, slate — in soft, layered pieces. Matte, slightly textured fabrics (washed linen, soft wool, suede) and tonal dressing are your signature; keep everything low-contrast, never stark or neon." },
    jewelry: { title: "Antiqued silver & soft stones", text: "Brushed or antiqued silver and matte rose gold with muted stones — labradorite, smoky quartz, grey pearl, soft amethyst. Choose understated, vintage-feeling pieces; bright polished metals overpower your softness." },
    meaning: "You are a Flemish still-life — muted, layered, and far richer than any first glance reveals. Soft does not mean small."
  },
  "Soft Autumn": {
    coords: { warmth: 0.4, value: 0.3, chroma: -0.7 },
    tagline: "Earthy, warm, and beautifully muted.",
    palette: [["Warm Taupe","#A8907F"],["Camel","#B59A75"],["Olive","#7F8055"],["Sage","#9BA577"],["Rust","#B57555"],["Mocha","#85674A"],["Soft Salmon","#D69585"],["Khaki","#A8A075"],["Pumpkin","#C2825A"],["Mushroom","#A89B8F"],["Forest","#5F6F4A"],["Soft Brick","#B56F5A"],["Wheat","#D6BC8F"],["Moss","#7F8555"],["Antique Gold","#B59755"],["Soft Coral","#C28575"],["Driftwood","#A89580"],["Faded Teal","#5F857F"]],
    neutrals: [["Camel","#B59A75"],["Warm Taupe","#A8907F"],["Mocha","#85674A"],["Cream","#EFE5D2"],["Soft Olive","#7F8055"]],
    avoid: [["Pure Black","#0A0A0A","Too severe"],["Pure White","#FAFAFA","Too stark"],["Hot Pink","#FF1A8A","Wrong everything"],["Icy Blue","#BDD9E8","Drains your warmth"],["Bright Cobalt","#2A4FB5","Too clear"]],
    metals: { title: "Antique gold, matte brass", text: "Brushed gold, antique brass, and bronze are your match. Skip anything polished, mirrored, or silver-bright.", swatches: ["#B59755","#A87932","#8A6F4A"] },
    prints: { title: "Earth-toned, organic", text: "Earth-toned florals, paisleys, batik, soft animal print. Medium scale, organic, low contrast." },
    makeup: { title: "Warm rose, brick, bronze", text: "Warm rose and soft brick lips, peach-warm blush, bronze and warm olive eyes. Foundation in soft-warm undertone.", swatches: ["#B57555","#D69585","#85674A"] },
    clothing: { title: "Earthy, warm, softly muted", text: "Warm, dusty earth tones — camel, olive, rust, soft brick — in relaxed, textured pieces. Suede, soft wool, washed cotton, and matte knits suit you; build tonal, low-contrast outfits and choose cream over pure white." },
    jewelry: { title: "Antique gold & warm stones", text: "Brushed or antique gold, brass, and bronze with warm muted stones — tiger's eye, amber, jade, bronze pearl, carnelian. Organic, hand-crafted pieces flatter; skip bright silver and high-shine finishes." },
    meaning: "You are a vineyard at dusk — warm, sun-faded, and quietly opulent. Your magic is in the murmur, not the shout."
  },
  "True Autumn": {
    coords: { warmth: 0.9, value: 0.2, chroma: -0.2 },
    tagline: "Spiced, regal, and richly grounded.",
    palette: [["Rust","#B5552A"],["Pumpkin","#C2702A"],["Mustard","#C29A2A"],["Olive","#7F7A2A"],["Forest","#3F5F2A"],["Bronze","#85552A"],["Burnt Sienna","#A85A2A"],["Caramel","#B07A4A"],["Brick","#9B4A3A"],["Terracotta","#C26A4A"],["Mahogany","#6B3322"],["Antique Gold","#B58A2A"],["Camel","#B59A65"],["Warm Brown","#7A4A2A"],["Avocado","#7F7F3A"],["Cinnamon","#A8552A"],["Teal","#2F5F5A"],["Cream","#EFE0BC"]],
    neutrals: [["Warm Brown","#7A4A2A"],["Camel","#B59A65"],["Olive","#7F7A2A"],["Cream","#EFE0BC"],["Mahogany","#6B3322"]],
    avoid: [["Pure White","#FAFAFA","Choose cream"],["Black","#0A0A0A","Too cool and harsh"],["Cool Pink","#E89BC4","Wrong undertone"],["Icy Blue","#BDD9E8","Drains warmth"],["Magenta","#C73883","Too cool and bright"]],
    metals: { title: "Antique gold, copper, bronze", text: "Burnished gold, copper, bronze — anything with warm patina. Silver looks anemic; rose gold confuses your warmth.", swatches: ["#B58A2A","#A87932","#7A4A2A"] },
    prints: { title: "Paisley, brocade, animal", text: "Paisley, brocade, autumn florals, animal print. Medium-to-large scale, rich and saturated — embrace pattern." },
    makeup: { title: "Brick, rust, copper", text: "Brick, rust, and warm berry lips, terracotta blush, copper and forest eyes. Warm-deep foundation; never pink.", swatches: ["#B5552A","#C2702A","#7A4A2A"] },
    clothing: { title: "Spiced, rich, grounded", text: "Rich, warm shades — pumpkin, forest, teal, terracotta, deep gold — in substantial fabrics: suede, tweed, leather, corduroy, heavier wool. Texture is your friend; lean fully warm and earthy, choosing deep warm neutrals over cool greys." },
    jewelry: { title: "Gold, copper & amber tones", text: "Warm yellow gold, copper, and bronze with rich earthy stones — amber, tiger's eye, topaz, carnelian, jade. Bold, substantial, artisanal pieces suit you; avoid cool silver and icy white stones." },
    meaning: "You are a Tuscan harvest — warm, dignified, and made for richness. Anything cool or cute weakens you; lean into spice."
  },
  "Deep Autumn": {
    coords: { warmth: 0.6, value: -0.7, chroma: 0.2 },
    tagline: "Smoldering, intense, and warm to the core.",
    palette: [["Mahogany","#5A2A1A"],["Burgundy Brown","#5A2A2F"],["Deep Olive","#3F3F1A"],["Forest","#1A3F2A"],["Burnt Orange","#B5552A"],["Espresso","#3A2A1A"],["Chocolate","#4A2F1A"],["Pumpkin","#C2702A"],["Eggplant","#3A1A2F"],["Tomato","#A8352A"],["Bronze","#85552A"],["Pine","#2A4A3A"],["Burgundy","#5A1A2A"],["Teal Deep","#1A3F4A"],["Brick","#7A2A1A"],["Caramel","#85552A"],["Mustard","#A87F2A"],["Plum","#4A1A3A"]],
    neutrals: [["Espresso","#3A2A1A"],["Charcoal","#2A2520"],["Chocolate","#4A2F1A"],["Cream","#EFE0BC"],["Bronze","#85552A"]],
    avoid: [["Pastels","#F5C9D6","Wash you out completely"],["Light Yellow","#F5E07A","Drains intensity"],["Pure White","#FAFAFA","Too stark"],["Powder Blue","#BFD6E5","Far too light and cool"],["Cool Pink","#E89BC4","Wrong everything"]],
    metals: { title: "Burnished gold, copper", text: "Deep, oxidized gold, antique copper, dark bronze. Anything too shiny or silvery undercuts your richness.", swatches: ["#85552A","#7A4A2A","#5A3F1A"] },
    prints: { title: "Bold paisley, brocade", text: "Bold paisley, deep brocade, animal print, autumn tartans. Larger scale, saturated, dramatic." },
    makeup: { title: "Brick, deep berry, copper", text: "Brick, deep berry, and burnished red lips, terracotta blush, espresso and copper eyes. Rich, warm-deep foundation.", swatches: ["#5A1A2A","#7A2A1A","#3A2A1A"] },
    clothing: { title: "Warm, deep, opulent", text: "Deep warm darks — chocolate, aubergine, forest, dark teal, brick — in luxe fabrics like velvet, leather, and heavy silk. You carry strong, rich color beautifully; build looks around a deep warm neutral and add one saturated accent." },
    jewelry: { title: "Rich gold & deep gemstones", text: "Warm gold and bronze with deep, warm stones — garnet, amber, dark topaz, onyx set in gold. Larger, bold statement pieces suit your depth; keep metals warm and finishes rich rather than icy or bright-silver." },
    meaning: "You are mahogany and bourbon — depth, warmth, and dignified intensity. You were never meant for light or pastel."
  },
  "Deep Winter": {
    coords: { warmth: -0.5, value: -0.8, chroma: 0.5 },
    tagline: "Velvet, jewel-toned, and unmistakably striking.",
    palette: [["True Black","#0A0A0A"],["Charcoal","#2A2A2A"],["Burgundy","#5A1A2F"],["Forest Pine","#1A3F2A"],["Royal Purple","#3A1A5A"],["Sapphire","#1A2F7A"],["Ruby","#7A1A3A"],["Emerald","#1A5A3A"],["Ice Pink","#E5B5C2"],["Pure White","#FAFAFA"],["Magenta","#A82A6F"],["Cobalt","#1A3FA8"],["Pine","#1A4A3A"],["Wine","#5A1A3A"],["Plum","#3A1A4A"],["Icy Blue","#BFD9E5"],["Black Cherry","#3A0A1A"],["Pewter","#5A5A5F"]],
    neutrals: [["True Black","#0A0A0A"],["Charcoal","#2A2A2A"],["Pure White","#FAFAFA"],["Deep Navy","#1A2A4A"],["Pewter","#5A5A5F"]],
    avoid: [["Orange","#E66A2C","Wrong temperature"],["Beige","#C9B59A","Drains your drama"],["Camel","#C19A6B","Too soft and warm"],["Mustard","#A87F2A","Sallows skin"],["Pastels","#F5C9D6","Wash you out"]],
    metals: { title: "Polished silver, platinum", text: "Bright cool silver, mirror platinum, gunmetal. Yellow gold reads jaundiced — skip it.", swatches: ["#C9C9C9","#A8A8A8","#5A5A5F"] },
    prints: { title: "High-contrast, jewel-toned", text: "High contrast graphics, bold florals on dark grounds, geometrics. Larger scale, sharp edges, jewel-toned." },
    makeup: { title: "Berry, ruby, smoky", text: "Berry, ruby, and true red lips, cool wine blush, smoky eyes in charcoal and plum. Cool-deep foundation.", swatches: ["#7A1A3A","#A82A6F","#3A1A5A"] },
    clothing: { title: "Velvet, jewel-toned, striking", text: "Deep, cool jewel tones — true red, emerald, sapphire, deep plum — against crisp black or charcoal. High contrast is your power: pair darks with icy brights. Choose smooth, rich fabrics (velvet, crisp wool, satin) and clean, dramatic lines." },
    jewelry: { title: "Cool silver & bold gemstones", text: "Silver, white gold, and platinum with deep, clear stones — sapphire, emerald, ruby, deep amethyst, white diamond. Bold, polished statement pieces flatter your contrast; avoid warm gold and dusty, muted stones." },
    meaning: "You are velvet and obsidian — built for jewel tones and high contrast. Soft and dusty are not your friends; lean into drama."
  },
  "True Winter": {
    coords: { warmth: -0.9, value: -0.4, chroma: 0.5 },
    tagline: "Crystalline, cool, and architecturally clear.",
    palette: [["True Black","#0A0A0A"],["Pure White","#FAFAFA"],["Royal Blue","#1A3FA8"],["Emerald","#1A6F3A"],["Ruby","#A82A3A"],["Magenta","#C73883"],["Pine","#1A4A2A"],["Sapphire","#1A2F7A"],["Icy Pink","#E5B5C9"],["Icy Blue","#BFD9E5"],["Icy Mint","#BFE5D2"],["Lemon Ice","#F5F0BC"],["Burgundy","#7A1A3A"],["Deep Purple","#3A1A5A"],["Pewter","#5A5A5F"],["Cool Red","#C2253A"],["Cobalt","#2A4FB5"],["Black Cherry","#3A0A1A"]],
    neutrals: [["True Black","#0A0A0A"],["Pure White","#FAFAFA"],["Charcoal","#2A2A2A"],["Pewter","#5A5A5F"],["Navy","#1A2A4A"]],
    avoid: [["Orange","#E66A2C","Wrong temperature"],["Camel","#C19A6B","Drains the cool"],["Mustard","#A87F2A","Sallows skin"],["Beige","#C9B59A","Reads muddy"],["Peach","#F5A572","Wrong warmth"]],
    metals: { title: "Polished silver, platinum", text: "Mirror silver and platinum are your truest match. Gold reads warm and yellow against your cool clarity.", swatches: ["#D6D6D6","#C9C9C9","#A8A8A8"] },
    prints: { title: "Crisp, geometric, black & white", text: "Black-and-white graphics, crisp polka dots, sharp geometrics. High contrast, clean edges, no fade." },
    makeup: { title: "True red, fuchsia, smoky", text: "True red, fuchsia, and berry lips, cool pink blush, smoky cool gray and ice eyes. Cool foundation; never warm.", swatches: ["#C2253A","#C73883","#1A3FA8"] },
    clothing: { title: "Crystalline, cool, architectural", text: "Pure, cool, high-contrast colors — true red, royal blue, magenta, pure white with black. Crisp, smooth fabrics and clean tailoring suit you; build sharp, defined silhouettes and avoid dusty or earthy tones." },
    jewelry: { title: "Silver, platinum & clear stones", text: "Cool silver, white gold, and platinum with icy, clear stones — diamond, sapphire, ruby, clear crystal. Sleek, polished, geometric pieces flatter; warm gold and muted organic stones dull your clarity." },
    meaning: "You are arctic clarity — built for contrast, crystal, and cool drama. Muted and warm soften your edges; stay clear."
  },
  "Bright Winter": {
    coords: { warmth: -0.4, value: -0.2, chroma: 0.9 },
    tagline: "Electric, glassy, and impossibly clear.",
    palette: [["Pure White","#FAFAFA"],["Hot Pink","#E84B8B"],["Magenta","#C73883"],["Bright Cobalt","#2A4FB5"],["Emerald","#1A8A4A"],["Bright Aqua","#3FBFC2"],["Lemon","#F5DC3A"],["Cherry Red","#D62A3A"],["Royal Purple","#5A2A8A"],["Fuchsia","#D63A8A"],["Icy Pink","#E5B5C9"],["Icy Blue","#BFD9E5"],["Black","#0A0A0A"],["Bright Coral","#F0625A"],["Bright Lime","#9FCC3A"],["Sapphire","#1A2FA8"],["Mint","#A8E5C9"],["Cyan","#2ABFDE"]],
    neutrals: [["Pure White","#FAFAFA"],["Black","#0A0A0A"],["Navy","#1A2A4A"],["Charcoal","#2A2A2A"],["Cool Gray","#A8A8A8"]],
    avoid: [["Beige","#C9B59A","Mutes your brilliance"],["Olive","#7F7A2A","Drains clarity"],["Rust","#B5552A","Wrong temperature"],["Mustard","#A87F2A","Sallows skin"],["Dusty Anything","#A89F95","Mutes your sparkle"]],
    metals: { title: "Polished silver, platinum", text: "Bright, mirror-finish cool metals. Gold and rose gold weigh you down — keep it crystalline.", swatches: ["#D6D6D6","#E5E5E5","#A8A8A8"] },
    prints: { title: "Bold, high-contrast, jewel-bright", text: "High contrast graphics in clear, saturated color. Bold florals, crisp stripes, anything jewel-bright." },
    makeup: { title: "Cherry red, hot pink, fuchsia", text: "Cherry red, hot pink, and fuchsia lips, clear pink blush, cool jewel-toned eyes. Clear, cool foundation.", swatches: ["#D62A3A","#E84B8B","#1A8A4A"] },
    clothing: { title: "Electric, glassy, ultra-clear", text: "Vivid, icy-bright colors — hot pink, electric blue, true emerald — with crisp white and black for contrast. Smooth, glossy fabrics and clean, sharp shapes hold your brightness; keep everything clear and high-contrast, never soft or dusty." },
    jewelry: { title: "Bright silver & vivid stones", text: "Polished silver, white gold, and platinum with brilliant clear stones — diamond, vivid sapphire, emerald, clear topaz. Sleek, high-shine statement pieces suit you; avoid antiqued metals and muted earth-tone stones." },
    meaning: "You are stained glass at noon — clear, jewel-bright, electric. Muted, dusty, and warm dim you; choose clarity always."
  }
};
